### DISCUSSION TITLE
Using Custom Fonts

### DISCUSSION THREAD

**Discussion by ShahriarKh** [zsviczian/obsidian-excalidraw-plugin#1537] [Show and tell]
I just want to post a simple way to use custom fonts.
The idea is to replace the default fonts (Helvetica for normal, Cascadia for monospace and Virgil for handwriting) with other fonts.

1. Create a new css snippet in Obsidian
2. Convert your font to base64 (you can use [this snippet](https://stackoverflow.com/a/59116157/7330316))
3. Declare a font face, using your own font, but with excalidraw font names

Example for replacing handwriting font by using "Balsamiq Sans" instead of "Virgil":
```css
@font-face {
  font-family: Virgil; /* excalidraw font name to replace */
  src: url("data:application/octet-stream;base64,AAEAAf+s......DMYytv"); /* (truncated) */
}
```

If embedded diagrams doesn't show font correctly, add this too:
```css
.excalidraw-svg text[font-family^="Virgil"] {
  font-family: /*your font name*/;
}

.excalidraw-svg text[font-family^="Helvetica"] {
  font-family: /*your font name*/;
}

.excalidraw-svg text[font-family^="Cascadia"] {
  font-family: /*your font name*/;
}
```
