### ISSUE TITLE
Cursor misalignement

### ISSUE THREAD

**Issue by davidedellagiustina** [zsviczian/obsidian-excalidraw-plugin#119]
No matter what I try, on my laptop the cursor is not aligned: when I try to drag a shape or object I need to aim like 1cm above the actual thing for it to be recognized. I suspect this is something related to the 4K resolution of my screen, but I cannot verify it.

**Screenshots**
How am I supposed to take a screenshot including the cursor? Windows automatically removes it.

**Desktop:**
 - OS: Windows 10
 - Obsidian version: 0.12.12
 - Excalidraw version: 1.2.13

**Comment by zsviczian** [comment]
I am sorry to hear that, it must be very frustrating :(. It is likely not related to 4k (alone), I also work on a 4k screen and do not experience the same issue.

Have you tried restarting Obsidian? Or try going to Excalidraw full screen mode and back? Closing excalidraw and opening it again?

Are you a long time Obsidian user? The reason for asking is that in some other cases updating Obsidian to the latest installer (Electron browser in the back end) resolved unexplainable errors…

**Comment by davidedellagiustina** [comment]
@zsviczian Thank you for your fast response!
I work on a 4k screen set to 175% scaling. I already tried setting it back to 100% and restarting Obsidian but still the same problem.
I started using Obsidian ~1 month ago, so not really a long-time user. My installer is v0.10.11, but I'm not sure how I can udate that.
However, I tried to disable all the custom extensions and themes I have installed, restarting and reloading Excalidraw, but nothing. The problem persists even toggling full-screen mode.

**Comment by zsviczian** [comment]
The installer version is a big difference. I am using installer 0.12.3. The installer defines the version of the Electron browser running under Obsidian. You should be able to update Obsidian installer by uninstalling and reinstalling using the latest installer from https://obsidian.md

**Comment by zsviczian** [comment]
I guess you will have no issues... but just to double-check, do you experience the same issue running [https://excalidraw.com](https://excalidraw.com)?

**Comment by davidedellagiustina** [comment]
I just managed to fix the problem, it was related to a custom CSS snippet I was using and that I completely forgot about. Since I use "Better PDF Plugin", I had some CSS code that changed some attributes of <canvas> elements - removing that CSS snippet fixes the problem.
However, now I need to find a way to apply those customizations only to the PDF canvases... D:

**Comment by zsviczian** [comment]
can you share the css so I can also understand why that caused an issue?

**Comment by davidedellagiustina** [comment]
Sure! Here it is:
```css
canvas {
  display: block;
  margin-top: 20pt;
  margin-bottom: 20pt;
  margin-left: auto;
  margin-right: auto;
  border-radius: 5pt;
}
```
Thank you for your patience

**Comment by zsviczian** [comment]
does better PDF not provide a class for their Canvas object? You can try excluding canvas.excalidraw__canvas from your CSS rule

**Comment by zsviczian** [comment]
https://stackoverflow.com/questions/2489674/how-to-create-a-css-rule-for-all-elements-except-one-class/2489736

**Comment by zsviczian** [comment]
```css
.not(excalidraw__canvas) canvas {
  display: block;
  margin-top: 20pt;
  margin-bottom: 20pt;
  margin-left: auto;
  margin-right: auto;
  border-radius: 5pt;
}
```

maybe this will work?

**Comment by davidedellagiustina** [comment]
I found another solution that I tested and works. It is based on the fact that "Better PDF Plugin" has its canvas included in an <a> tag:
```css
a > canvas {
  display: block;
  margin-top: 20pt;
  margin-bottom: 20pt;
  margin-left: auto;
  margin-right: auto;
  border-radius: 5pt;
}
```
