### ISSUE TITLE
BUG: Hover preview broken in 1.6.0

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#1770]
Also effects excalidraw markdown reading mode

**Comment by zsviczian** [comment]
temporary fix, add this css snippet 

```css
.popover .excalidraw-svg {  
  width: 100%;
  max-width: inherit;
  height: 100%;
  max-height: inherit;
}
```
