### ISSUE TITLE
BUG: textarea caret color (not visible in Obsidian 1.6.0 when Obsidian is in dark mode and excalidraw in light)

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#1772]
should add to dynamic styling

```css
.excalidraw textarea, .excalidraw input {
  caret-color: initial;
}
```
