### ISSUE TITLE
about css

### ISSUE THREAD

**Issue by zhl111** [zsviczian/obsidian-excalidraw-plugin#286]
1, I know the reason why the font does not change color: if the file has frontmatter, the font will not change color.Unless it must be added"excalidraw-font-color: xxx",Otherwise it ignores the colors in the plugin settings,In black themes only white is displayed.
2, I loaded the css, but found that it does not display the full。Even if I change the settings, it doesn't show the whole thing.The text can be displayed completely, only the bottom horizontal line will not be displayed
![image](https://user-images.githubusercontent.com/29135984/143882143-c8858787-3142-4e6d-87a0-2ebabcd43920.png)
![image](https://user-images.githubusercontent.com/29135984/143882997-6342c1a0-74a0-4802-8fe8-326149915e91.png)

**Comment by zsviczian** [comment]
Thanks. I will test this out.

**Comment by zsviczian** [comment]
Thank you. 
I fixed 1) in 1.4.15
For 2) try adding. Because of all the different css in Obsidian, I was not able to write code that measures the exact correct height of the text/image.
```css
.excalidraw-md-host {
  margin-bottom: 5px; 
}
```

**Comment by zhl111** [comment]
1,The outer border line does not keep the same color as the text
2,Little space for underline and text, not aligned with the rest
![image](https://user-images.githubusercontent.com/29135984/143965870-806c7214-36f0-4568-b23e-b4d88bbd28d9.png)
thanks

**Comment by zsviczian** [comment]
The color you can solve with CSS. The sizing I will need to do some change to the code. I tried CSS, but the way I measure the object height interferes with css sizing.

```css
foreignObject {
 border: 2px solid;
 color: skyblue;
 padding-bottom: 10px;
}
```

**Comment by zhl111** [comment]
"padding-bottom:" is OK to put under this
![image](https://user-images.githubusercontent.com/29135984/144019096-2e3ea570-8126-4040-854c-edb725efee73.png)
 "padding-bottom:" is placed under this and there is no change
![image](https://user-images.githubusercontent.com/29135984/144019450-6344761d-66bf-4a80-b7d6-9cf151c8886b.png)

**Comment by zsviczian** [comment]
what do you mean?
You can set the export scale of PNGs in settings:
![image](https://user-images.githubusercontent.com/14358394/144019774-640eecda-8e0c-4207-ada0-954833aa3dfd.png)

SVGs are inherently scalable.

When you embed PNG and/or svg in documents in Obsidian you can use [[file|widthxheight]] to size the image.
You can also set the size of embedded excalidraw images as described in the Plugin readme:
![image](https://user-images.githubusercontent.com/14358394/144020096-28890709-1763-45df-8524-b6bec80196e8.png)

**Comment by zhl111** [comment]
sorry,I was too careless and overlooked that you had added this feature.
Excalidraw maybe we can achieve the display effect of this note software ah [Heptabase](https://heptabase.com/)

**Comment by zsviczian** [comment]
instead of the `foreignObject` you can also style the SVG element.
Try this:
```css
svg {
	border: 2px solid;
	color: skyblue;
	/*padding-bottom: 5px;*/
	transform: scale(0.98);
}
```

**Comment by zsviczian** [comment]
I added a footer element.  Try this formatting:

```css
.excalidraw-md-host {
 padding: 0px 15px;
}

.excalidraw-md-footer {
  height: 5 px;
  display: block;
}

foreignObject {
 background-color: whitesmoke;
}

svg {
  border: 2px solid;
  transform: scale(0.985);
  color: skyblue;
}
```
