### ISSUE TITLE
Show markdown table make with the advanced table plugin when embedding markdown file in Excalidraw

### ISSUE THREAD

**Issue by slimhk45** [zsviczian/obsidian-excalidraw-plugin#316]
When I drag a markdown file to embed it in excalidraw it would be cool to be able to view markdown table too.

**Comment by zsviczian** [comment]
You can. All you need is the appropriate CSS. Use this as a starter... or am I misunderstanding something?

**Comment by slimhk45** [comment]
> You can. All you need is the appropriate CSS. Use this as a starter... or am I misunderstanding something?

I don't the column separator. There is a doc to change the css?

**Comment by zsviczian** [comment]
It does take a bit of trial and error and requires some css skills...

https://youtu.be/K6qZkTz8GHs

You can view the most recent markdown SVG generated by opening the developer console and typing in the following command. This should help you debug the css you are creating.
`ExcalidrawAutomate.mostRecentMarkdownSVG`

**Comment by slimhk45** [comment]
Okay I'll try it. It's a bit complicated right now, I hope there will be a simpler alternative to stylize markdown table with a simple header to put in the top of the markdown page like you have shown in your video for the default font and the default color of the embedded page.

**Comment by zsviczian** [comment]
The challenge is everyone wants to format something else. Tables, bullet points, text alignment, font-face, the border around the page, etc. The most flexible approach is to provide a means to add your custom css.

What would be nice is if some of the theme builder community found interest in developing css themes for markdown embeds.

In the meantime, I googled formatting tables with css for you. Here's a slightly altered version of the first page found by Google [Creating beautiful HTML tables with CSS](https://dev.to/dcodeyt/creating-beautiful-html-tables-with-css-428l):

![image](https://user-images.githubusercontent.com/14358394/147406415-9678a793-802c-454c-af4f-fbd585026195.png)

```css
table {
    border-collapse: collapse;
    margin: 25px 0;
    font-size: 0.9em;
    /*font-family: sans-serif;*/
    min-width: 400px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
}

thead tr {
    background-color: #009879;
    color: #ffffff;
    text-align: left;
}

th,
td {
    padding: 12px 15px;
}

tbody tr {
    border-bottom: 1px solid #dddddd;
}

tbody tr:nth-of-type(even) {
    background-color: #f3f3f3;
}

tbody tr:last-of-type {
    border-bottom: 2px solid #009879;
}

tbody tr.active-row {
    font-weight: bold;
    color: #009879;
}
```
