### ISSUE TITLE
Move status bar to the left in case of tray-mode, left-handed mode

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-excalidraw-plugin#764]
```css
.status-bar {
  left: var(--ribbon-width);
  right: unset;
  border-radius: 0 var(--radius-m) 0 0;
}
```
