### ISSUE TITLE
FR: Compact Property Panel

### ISSUE THREAD

**Issue by Zoestra** [zsviczian/obsidian-excalidraw-plugin#972]
The property panel takes up too much space on mobile (ipad specifically). It takes up a large portion of the screen, and makes using a pen frustrating.

I propose that a compact menu with flyouts for each option like in the attached mockup.

![image_2023-01-12_211701308](https://user-images.githubusercontent.com/79121105/212242996-bafb9551-9358-4082-bd11-282896ba452f.png)

**Comment by zsviczian** [comment]
Try tray mode.
You'll find the tray mode button on the Obsidian Panel and on the Command Palette

**Comment by Zoestra** [comment]
Tray mode is an improvement, but it still has some shortcomings. first, the option to turn it on is buried and difficult to find. second you have open and close it every time you want to access it. this is why i think that a compact menu would be a better solution.

**Comment by zsviczian** [comment]
I don't disagree, however, once you find it you know where it is so being burried is no longer an issue, and more importantly from an implementation perspective it requires minimum extra work over what excalidraw.com offers out of the box, however it is still better.

You see, our objectives are different. I am a hobby hacker (not even a developer) working on this plugin in my free time, building it primarily for myself, but making it available to the Obsidian community as well. From a sustainability perspective, I have no other choice but to look for the solutions that require the least effort to port excalidraw to Obsidian in a way that it enables linking and deconstruction of images. I avoid any large scale development in the excalidraw codebase, but rather focus on extras built around it. The menu would need to be implemented in the excalidraw package.

However, if you feel strongly about the menu, I recommend developing a new menu for excalidraw.com and submitting it as a PR. Once it is available on excalidraw.com, I will happily deploy it to Obsidian.

**Comment by Zoestra** [comment]
if you dont have any stylistic objections to a feature like this, i'll give a go at figuring it out myself. I'm a CS student and need a project to tide me over through the next few quarters while i dont have any classes. 
i dont currently know any JS/TS or CSS, but im starting to look into it. This feels like a decent issue to start exploration with.

**Comment by dimateos** [comment]
Hey! I tweak a lot the CSS, this is the compact side panel I use.
You can tweak it further as it does some extra things.

<img width="215" height="721" alt="Image" src="https://github.com/user-attachments/assets/622b8892-e3b0-47ba-b6a7-72cf329d69f2" />

```css
/* HIDE... */
.HintViewer,
.help-icon {
  opacity: 0.25 !important;
  display: none !important;
}

/* TOOLS */
.Island {
  /*background-color: rgba(255, 255, 255, 0.329) !important;*/
  /*opacity: 0.25 !important;*/
  background-color: rgba(175, 175, 175, 0.329) !important;
}

/* compact manu */
.selected-shape-actions {
  display: block !important;
}

/* delete by name */
.selected-shape-actions-container .buttonList button[aria-label="delete" i]
,.selected-shape-actions-container .buttonList button[aria-label="duplicate" i]
,.selected-shape-actions-container .buttonList button[aria-label*="link" i]
,.selected-shape-actions-container .buttonList button[aria-label*="image" i]
{
    display: none !important;
}

/* hide titles (of some) */
.selected-shape-actions-container fieldset > legend:has(+ .buttonList) {
    display: none !important;
}
```

Regards
